; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = uno_oled

[env:uno_lcd]
platform = atmelavr
board = uno
framework = arduino
build_flags = -DUSE_OLED_DISPLAY=0
lib_deps = 
	adafruit/DHT sensor library@1.4.7
	adafruit/Adafruit Unified Sensor@1.1.15
	marcoschwartz/LiquidCrystal_I2C@1.1.4
lib_ignore = 
	Adafruit SSD1306
	Adafruit GFX Library
build_src_filter = 
	+<*>
	-<OBSOLETE_*>

[env:uno_oled]
platform = atmelavr
board = uno
framework = arduino
build_flags = -DUSE_OLED_DISPLAY=1
lib_deps = 
	adafruit/DHT sensor library@1.4.7
	adafruit/Adafruit Unified Sensor@1.1.15
	adafruit/Adafruit SSD1306@2.5.7
	adafruit/Adafruit GFX Library@1.11.9
lib_ignore = marcoschwartz/LiquidCrystal_I2C@1.1.4
build_src_filter = 
	+<*>
	-<OBSOLETE_*>

[env:nano_oled]
platform = atmelavr
board = nanoatmega328
framework = arduino
build_flags = -DUSE_OLED_DISPLAY=1
lib_deps = 
	adafruit/DHT sensor library@1.4.7
	adafruit/Adafruit Unified Sensor@1.1.15
	adafruit/Adafruit SSD1306@2.5.7
	adafruit/Adafruit GFX Library@1.11.9
lib_ignore = marcoschwartz/LiquidCrystal_I2C@1.1.4
build_src_filter = 
	+<*>
	-<OBSOLETE_*>
